Feature
roshan-bajgain/My-portfolio pull request #1
Opened 2021-08-18 10:40 UTC by roshan-bajgain

This is my portfolio first page.
The objective of the page is to use linter, github flow, documentation of repo.
I created My-portfolio repo and cloned into local machine.
I added HTML and css file and extract background image and some logo and implemented those tools

2021-08-18 11:00 UTC, mke2111 requested changes
### Hey @roshan-bajgain, 

**This is a great project you have going on, well-done lad**. 

   
**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

## Required Changes ♻️
_Check the inline comments under the review for sections to improve._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-18 11:01 UTC, mke2111 commented on index.html
> +      <h1>My Logo</h1>
- [ ] Enclose the logo within `a` tags. This will help to always redirect to a desired webpage.

2021-08-18 11:03 UTC, mke2111 commented on index.html
> +        <P class="para">I’m Roshan <br> Glad to see<br> you!</P>
- [ ] I recommend you to use `hx` tags for all titles. This is a title/heading so change the `p` tag to a `hx` tag, preferebly `h1` tag

2021-08-18 11:05 UTC, mke2111 commented on index.html
> +          <img class="img4" src="Vector1.png" alt="logo of social media">
- [ ] For all these icons, group them using a `ul` tag. 
- [ ] For each icon, list it in an `li` tag
- [ ] Still, within the `li` tag, use `a` tag for each icon.

2021-08-18 11:08 UTC, mke2111 commented on index.html
> +</html>
- [ ] Please consider the design template specifications used by figma. Your design is not responsive for all mobile screens. Adjust your design layout and positions appropriately.
![Screenshot from 2021-08-18 13-59-12](https://user-images.githubusercontent.com/65501535/129887855-7c1909bb-a8bd-4d54-8084-c8392d71cb7f.png)

2021-08-19 09:21 UTC, Emmyn5600 commented on index.html
> +      <h1>My Logo</h1>
Well solved

2021-08-19 09:21 UTC, Emmyn5600 commented on index.html
> +        <P class="para">I’m Roshan <br> Glad to see<br> you!</P>
Well done

2021-08-19 09:21 UTC, Emmyn5600 commented on index.html
> +          <img class="img4" src="Vector1.png" alt="logo of social media">
Well solved

2021-08-19 09:23 UTC, Emmyn5600 commented on index.html
> +</html>
Well done

2021-08-19 09:26 UTC, Emmyn5600 approved these changes
Hi, 

Good job so far! 👏🏼 @roshan-bajgain 

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous TSEs
 
Optional suggestion

#### To remove unnecessary files in the root folder, you can create a new folder called `assets` to keep all images 

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-08-19 15:25 UTC, merged