Contact-form
roshan-bajgain/My-portfolio pull request #3
Opened 2021-08-24 15:11 UTC by roshan-bajgain

I created new branch name feature.
I created section tag inside feature branch and added background.
I wrote header and paragraph and work in form.
lastly I created button.

2021-08-24 15:13 UTC, AshakaE requested changes
### Hi @roshan-bajgain   🙋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request ‼ 

You have submitted a project, that a failing linter check ❌

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-08-25 05:52 UTC, DanteAlonsoHT requested changes
<h1> Status: Required Changes 🚫 </h1>

Hi @roshan-bajgain and @Debas-31! 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-25 05:52 UTC, DanteAlonsoHT commented on index.html
> +        <form action="#" method="POST">
- [ ] `action` value should be similar to https://formspree.io/f/{form_id}, please use [Formspree service](https://formspree.io/html) to add the functionability for your form.

2021-08-25 05:52 UTC, DanteAlonsoHT commented on index.html
> +          <input type="text" class="fomm" id="name" name="User-name" placeholder="Roshan" minlength="1" maxlength="30"><br>
- [ ]  Your input to add the name should be required, please the `required` HTML attribute for this `input`. For instance:
```
<input required>
```

- [ ] Kindly, you can use another placeholder text to make it more descriptive like "First Name, Last Name or Type your Name"

2021-08-25 05:52 UTC, DanteAlonsoHT commented on index.html
> +          <textarea class="text" id="msg" name="user-message" placeholder="Write your message here" maxlength="500"></textarea>
- [ ] You should add the `required` HTML attribute for your `textarea as I mentioned previously with your input for the name.

2021-08-25 05:52 UTC, DanteAlonsoHT commented on index.html
> +          </div>
- [ ] Your `type` HTML attribute should have the value "submit" instead of "button" to send the data (inside your form) properly.

- [ ] Please, add this CSS style for all your buttons in order to improve the UX for your design when you hover them. 
```
button:hover {
  cursor: pointer;
}
```

2021-08-25 07:02 UTC, DanteAlonsoHT requested changes
<h1>Status: Invalidating project 🚫 </h1>

Hi @roshan-bajgain and @Debas-31, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project, that one of the linters was not passed successfully, please fix it 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._ 😉

2021-08-25 07:44 UTC, DanteAlonsoHT requested changes
<h1>Status: Changes Required 🚫 ♻️  </h1>

Hi @roshan-bajgain and  @Debas-31, 

Great work on making the changes requested 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions

- [ ] [OPTIONAL] Add the same behavior from your submit button to all your button in your app 😉 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-25 07:44 UTC, DanteAlonsoHT commented on index.html
> +        <form action="https://kwesforms.com/api/foreign/forms/pt0BiL3Vhynr5CDME4lI" class="kwes-form" method="POST">
- [ ] It's a nice implementation, but according to the project requirements you should use [Formspree service](https://formspree.io/html) however I highlight your way to go beyond the only project requirements.

- [ ] `action` value in your form should be similar to `https://formspree.io/f/{form_id}`, please go to [Formspree service](https://formspree.io/html) to see how to add the id properly.

2021-08-25 08:41 UTC, DanteAlonsoHT approved these changes
<h1>Status: Approve 🥇 ✔</h1>
Hi @roshan-bajgain and @Debas-31, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

<img src="https://media.giphy.com/media/aNqEFrYVnsS52/giphy.gif" width="100%">

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-25 08:55 UTC, merged